
on:
  pull_request:
    branches:
      - master

name: Build Homely
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: |
          cd $HOME/work/homely
          mkdir src
          mkdir bin
          mkdir pkg
          export GOPATH=$HOME/work/homely
          mv homely src
          go test homely/...

