
on:
  pull_request:
    branches:
      - master

name: Build Homely
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Fetch and run dependencies
        run: |
          cd $HOME/work/homely
          mkdir src
          mkdir bin
          mkdir pkg
          export GOPATH=$HOME/work/homely
          export GOBIN=$GOPATH/bin
          export PATH=$GOBIN:$PATH
          mv homely src
          go get golang.org/x/sys/unix
          go get -u github.com/kardianos/govendor
          cd $GOPATH/src/homely
          govendor sync
          go test homely/...
